//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class AgentTargetDestinationsMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/AgentTargetDestinations";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] agents;
        public Geometry.PointMsg[] targets;

        public AgentTargetDestinationsMsg()
        {
            this.agents = new Geometry.PoseMsg[0];
            this.targets = new Geometry.PointMsg[0];
        }

        public AgentTargetDestinationsMsg(Geometry.PoseMsg[] agents, Geometry.PointMsg[] targets)
        {
            this.agents = agents;
            this.targets = targets;
        }

        public static AgentTargetDestinationsMsg Deserialize(MessageDeserializer deserializer) => new AgentTargetDestinationsMsg(deserializer);

        private AgentTargetDestinationsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.agents, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.targets, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.agents);
            serializer.Write(this.agents);
            serializer.WriteLength(this.targets);
            serializer.Write(this.targets);
        }

        public override string ToString()
        {
            return "AgentTargetDestinationsMsg: " +
            "\nagents: " + System.String.Join(", ", agents.ToList()) +
            "\ntargets: " + System.String.Join(", ", targets.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
