//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class AgentTargetPositionsMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/AgentTargetPositions";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] agents;
        //  Lista posizioni agenti
        public float[] target_distances;
        //  Lista distance tra agente e target
        public Geometry.PointMsg[] target_positions;
        // Lista posizioni target

        public AgentTargetPositionsMsg()
        {
            this.agents = new Geometry.PoseMsg[0];
            this.target_distances = new float[0];
            this.target_positions = new Geometry.PointMsg[0];
        }

        public AgentTargetPositionsMsg(Geometry.PoseMsg[] agents, float[] target_distances, Geometry.PointMsg[] target_positions)
        {
            this.agents = agents;
            this.target_distances = target_distances;
            this.target_positions = target_positions;
        }

        public static AgentTargetPositionsMsg Deserialize(MessageDeserializer deserializer) => new AgentTargetPositionsMsg(deserializer);

        private AgentTargetPositionsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.agents, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.target_distances, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.target_positions, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.agents);
            serializer.Write(this.agents);
            serializer.WriteLength(this.target_distances);
            serializer.Write(this.target_distances);
            serializer.WriteLength(this.target_positions);
            serializer.Write(this.target_positions);
        }

        public override string ToString()
        {
            return "AgentTargetPositionsMsg: " +
            "\nagents: " + System.String.Join(", ", agents.ToList()) +
            "\ntarget_distances: " + System.String.Join(", ", target_distances.ToList()) +
            "\ntarget_positions: " + System.String.Join(", ", target_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
