//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class AgentStatusMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/AgentStatus";
        public override string RosMessageName => k_RosMessageName;

        public string agent_id;
        public string[] target_ids;
        public float[] target_distances;

        public AgentStatusMsg()
        {
            this.agent_id = "";
            this.target_ids = new string[0];
            this.target_distances = new float[0];
        }

        public AgentStatusMsg(string agent_id, string[] target_ids, float[] target_distances)
        {
            this.agent_id = agent_id;
            this.target_ids = target_ids;
            this.target_distances = target_distances;
        }

        public static AgentStatusMsg Deserialize(MessageDeserializer deserializer) => new AgentStatusMsg(deserializer);

        private AgentStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.agent_id);
            deserializer.Read(out this.target_ids, deserializer.ReadLength());
            deserializer.Read(out this.target_distances, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_id);
            serializer.WriteLength(this.target_ids);
            serializer.Write(this.target_ids);
            serializer.WriteLength(this.target_distances);
            serializer.Write(this.target_distances);
        }

        public override string ToString()
        {
            return "AgentStatusMsg: " +
            "\nagent_id: " + agent_id.ToString() +
            "\ntarget_ids: " + System.String.Join(", ", target_ids.ToList()) +
            "\ntarget_distances: " + System.String.Join(", ", target_distances.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
