//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class AgentTargetMsgMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/AgentTargetMsg";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg agent_pose;
        //  Posizione dell'agente
        public Geometry.PoseMsg target_pose;
        //  Posizione del target assegnato

        public AgentTargetMsgMsg()
        {
            this.agent_pose = new Geometry.PoseMsg();
            this.target_pose = new Geometry.PoseMsg();
        }

        public AgentTargetMsgMsg(Geometry.PoseMsg agent_pose, Geometry.PoseMsg target_pose)
        {
            this.agent_pose = agent_pose;
            this.target_pose = target_pose;
        }

        public static AgentTargetMsgMsg Deserialize(MessageDeserializer deserializer) => new AgentTargetMsgMsg(deserializer);

        private AgentTargetMsgMsg(MessageDeserializer deserializer)
        {
            this.agent_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_pose);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "AgentTargetMsgMsg: " +
            "\nagent_pose: " + agent_pose.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
