//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class RobotCommunicationMsgMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/RobotCommunicationMsg";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public Geometry.PointMsg target_position;

        public RobotCommunicationMsgMsg()
        {
            this.robot_id = 0;
            this.target_position = new Geometry.PointMsg();
        }

        public RobotCommunicationMsgMsg(int robot_id, Geometry.PointMsg target_position)
        {
            this.robot_id = robot_id;
            this.target_position = target_position;
        }

        public static RobotCommunicationMsgMsg Deserialize(MessageDeserializer deserializer) => new RobotCommunicationMsgMsg(deserializer);

        private RobotCommunicationMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            this.target_position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.target_position);
        }

        public override string ToString()
        {
            return "RobotCommunicationMsgMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\ntarget_position: " + target_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
