//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Script
{
    [Serializable]
    public class RobotCommunicationMsg : Message
    {
        public const string k_RosMessageName = "Script/RobotCommunication";
        public override string RosMessageName => k_RosMessageName;


        public RobotCommunicationMsg()
        {
        }
        public static RobotCommunicationMsg Deserialize(MessageDeserializer deserializer) => new RobotCommunicationMsg(deserializer);

        private RobotCommunicationMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "RobotCommunicationMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
